import ManagerTemplate from "@/components/ManagerTemplate";
import MenuList from "../menuList";
export const metadata = {
  title: "User | Ordering System",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <ManagerTemplate title="User" id="user" menuList={MenuList}>
      {children}
    </ManagerTemplate>
  );
};
export default RootLayout;
